#!/usr/bin/python
import re
import sys
import commands
import optparse

########################
#command line options processing 
#######################

parser = optparse.OptionParser()

parser.add_option('-w', help='arguments', action='store',type='int',default='10')
parser.add_option('-c', help='arguments', action='store',type='int',default='10')
parser.add_option('-S', help='arguments', action='store',type='string',default='')

options, args = parser.parse_args()

critical = options.c
warning = options.w

command = "/usr/bin/sudo /usr/sbin/exiqgrep -ir " + options.S + "  | wc -l"

#################

Result = commands.getstatusoutput(command)
Queue = int(Result[1])

#Determine state to pass to Nagios
#CRITICAL = 2
#WARNING = 1
#OK = 0

if Queue >= critical:
    print "CRITICAL" + options.S + " Delivering: %d Messages " % (int(Queue))
    sys.exit(2)
elif Queue >= warning:
    print "AN WARNING on " + options.S + " Delivering: %d Messages " % (int(Queue))
    sys.exit(1)
else:
    print options.S + " Delivering is  OK: %d Messages" % (int(Queue))
    sys.exit(0)
